# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    #container: ubuntu:18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: bash
        run: |
          cat <<EOF > docker-script.sh
          #!/bin/bash
          DEBIAN_FRONTEND=noninteractive apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qqy install ccache build-essential python python-pip sudo libgcc-5-dev uuid-dev nasm iasl git gcc-aarch64-linux-gnu wget zip
          wget "https://github.com/tianocore/edk2/releases/download/vUDK2018/edk2-vUDK2018.tar.gz" -O edk2.tar.gz
          tar zxf edk2.tar.gz && rm -rf edk2.tar.gz
          sudo mv edk2-* /usr/local/edk2-vUDK2018
          pushd /usr/local/edk2-vUDK2018
          source edksetup.sh
          sed -i 's/-Werror //g' BaseTools/Source/C/Makefiles/header.makefile
          cat BaseTools/Source/C/Makefiles/header.makefile
          sed -i 's/^ACTIVE_PLATFORM .*/ACTIVE_PLATFORM = MdePkg\/MdePkg.dsc/g' Conf/target.txt
          sed -i 's/^TARGET .*/TARGET = RELEASE/g' Conf/target.txt
          sed -i 's/^TARGET_ARCH .*/TARGET_ARCH = AARCH64/g' Conf/target.txt
          sed -i 's/^TOOL_CHAIN_TAG .*/TOOL_CHAIN_TAG = GCC5/g' Conf/target.txt
          sed -i 's/ENV(GCC5_AARCH64_PREFIX)/\/usr\/bin\/aarch64-linux-gnu-/g' Conf/tools_def.txt
          cat Conf/target.txt
          cat Conf/tools_def.txt
          make -C BaseTools
          make -C BaseTools/Source/C
          build
          popd
          wget "https://github.com/rodriguezst/rEFInd/archive/refs/heads/GopRotate.tar.gz"
          tar zxf GopRotate.tar.gz && rm GopRotate.tar.gz
          pushd rEFInd-GopRotate
          rm -rf GopRotate
          git clone "https://github.com/apop2/GopRotate" /usr/local/edk2-vUDK2018/GopRotate
          #sed -i 's/-O binary/--target=efi-app-aarch64/g' Make.common
          make edk2 OMIT_SBAT=1 ARCH=aarch64
          make fs_edk2 OMIT_SBAT=1 ARCH=aarch64
          find . | grep ".efi"
          echo "***** End of Docker Script *****"
          EOF
          chmod +x docker-script.sh
          docker run --rm -v $(pwd):$(pwd) -w $(pwd) ubuntu:18.04 ./docker-script.sh
          find . | grep refind_aa64.efi
      - uses: actions/upload-artifact@v4
        with:
          name: refind
          path: ${{ github.workspace }}/rEFInd-0.14.2/*

